/////////////-----------------Login Action------------------///////////
export const LOGIN_ADMIN = "LOGIN_ADMIN";
export const LOGIN_SELLER = "LOGIN_SELLER";
export const LOGIN_ADMIN_SUCCESS = "LOGIN_ADMIN_SUCCESS";
export const LOGIN_ADMIN_FAIL = "LOGIN_ADMIN_FAIL";

export const GET_ADMIN_DETAILS = "GET_ADMIN_DETAILS";
export const GET_ADMIN_DETAILS_SUCCESS = "GET_ADMIN_DETAILS_SUCCESS";
export const GET_ADMIN_DETAILS_FAIL = "GET_ADMIN_DETAILS_FAIL";

export const GET_SELLER_DETAILS = "GET_SELLER_DETAILS";
export const GET_SELLER_DETAILS_SUCCESS = "GET_SELLER_DETAILS_SUCCESS";
export const GET_SELLER_DETAILS_FAIL = "GET_SELLER_DETAILS_FAIL";

export const LOGOUT_ADMIN = "LOGOUT_ADMIN";
export const CHANGE_PROFILE_IMAGE = "CHANGE_PROFILE_IMAGE";
